name: Autocoder Workflow

on:
  issues:
    types:
      - labeled

jobs:
  autocoder-job:
    if: contains(github.event.label.name, 'autocoder-bot') # Check if the issue has the 'autocoder-bot' label
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make the script executable
        run: chmod +x autocoder-script.sh

      - name: Run the autocoder script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          ./scripts/autocoder-script.sh $GITHUB_TOKEN $REPOSITORY $ISSUE_NUMBER $OPENAI_API_KEY

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: autocoder-artifact
          path: autocoder-bot/

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: autocoder-artifact
          path: autocoder-artifact/

      - name: List downloaded files
        run: ls -R autocoder-artifact/