name: Workflow Name

# Trigger on push events
on: push

jobs:
  job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Greeting Message
        run: echo "Hello, world"